# Generated by Django 5.0.13 on 2025-12-01 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('temperatura_ideal', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('es_peligroso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoría de Almacén',
                'verbose_name_plural': 'Categorías de Almacén',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('licencia_manejo_montacargas', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado de Almacén',
                'verbose_name_plural': 'Empleados de Almacén',
            },
        ),
        migrations.CreateModel(
            name='ProveedorAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('direccion_proveedor', models.CharField(max_length=255)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Almacén',
                'verbose_name_plural': 'Proveedores de Almacén',
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_sku', models.CharField(max_length=50, unique=True)),
                ('stock_actual', models.IntegerField()),
                ('ubicacion_almacen', models.CharField(max_length=100)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_producto.categoriaalmacen')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_producto.proveedoralmacen')),
            ],
            options={
                'verbose_name': 'Producto de Almacén',
                'verbose_name_plural': 'Productos de Almacén',
            },
        ),
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inventario', models.DateField()),
                ('stock_sistema', models.IntegerField()),
                ('stock_fisico', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado_realizo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_realizados', to='app_producto.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='app_producto.productoalmacen')),
            ],
            options={
                'verbose_name': 'Inventario Físico',
                'verbose_name_plural': 'Inventarios Físicos',
            },
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.IntegerField()),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('num_factura_compra', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado_recepcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_recibidas', to='app_producto.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='app_producto.productoalmacen')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='app_producto.proveedoralmacen')),
            ],
            options={
                'verbose_name': 'Entrada de Producto',
                'verbose_name_plural': 'Entradas de Productos',
            },
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.IntegerField()),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('destino', models.CharField(max_length=100)),
                ('id_cliente_salida', models.IntegerField(blank=True, null=True)),
                ('num_pedido_salida', models.CharField(max_length=50)),
                ('motivo_salida', models.TextField(blank=True, null=True)),
                ('empleado_despacho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_despachadas', to='app_producto.empleadoalmacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='app_producto.productoalmacen')),
            ],
            options={
                'verbose_name': 'Salida de Producto',
                'verbose_name_plural': 'Salidas de Productos',
            },
        ),
    ]
