# Generated by Django 5.0.13 on 2025-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariofisico',
            name='fecha_inventario',
            field=models.DateField(auto_now_add=True),
        ),
    ]
