# Generated by Django 5.0.13 on 2025-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0002_alter_inventariofisico_fecha_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariofisico',
            name='fecha_inventario',
            field=models.DateField(),
        ),
    ]
